import {
  useCallback,
  useEffect,
  useRef,
  useState,
  type FormEvent,
} from "react";
import {
  Activity,
  ArrowRight,
  CheckCheck,
  ChevronRight,
  ClipboardCheck,
  Factory,
  LayoutDashboard,
  LogOut,
  Menu,
  Play,
  RefreshCw,
  ShieldCheck,
  Truck,
  X,
} from "lucide-react";
import {
  api,
  date,
  label,
  scoped,
  setCsrf,
  string,
  type Kpis,
  type RecordData,
  type Run,
  type Scenario,
  type Scope,
  type Session,
} from "./api";
import {
  Badge,
  Empty,
  ErrorBox,
  Loading,
  Modal,
  useQuery,
  useRoute,
} from "./ui";
import { Overview } from "./Overview";
import { IncidentDetail } from "./IncidentDetail";
import { Approvals } from "./Approvals";
import { Reliability } from "./Reliability";
import { rememberScope, restoreScope } from "./scope-preference";

function Brand() {
  return (
    <a className="brand" href="#/overview" aria-label="APIC overview">
      <span className="brand-symbol">
        <Activity size={24} />
      </span>
      <span>
        <b>APIC</b>
        <small>Incident control</small>
      </span>
    </a>
  );
}
function Login({ onLogin }: { onLogin: (session: Session) => void }) {
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<Error | null>(null);
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const form = new FormData(event.currentTarget);
    setBusy(true);
    setError(null);
    try {
      const session = await api<Session>("/api/auth/login", {
        username: form.get("username"),
        password: form.get("password"),
      });
      setCsrf(session.csrf_token);
      onLogin(session);
    } catch (err) {
      setError(err as Error);
    } finally {
      setBusy(false);
    }
  }
  return (
    <div className="login-layout">
      <aside className="login-story">
        <Brand />
        <div>
          <span className="eyebrow">AI PRODUCTION INCIDENT CONTROL</span>
          <h1>
            Clarity when
            <br />
            operations change.
          </h1>
          <p>
            From an unstructured incident to a verified impact assessment, a
            human-approved response and an auditable action trail.
          </p>
          <div className="login-principles">
            <span>
              <CheckCheck size={18} /> Verified operational facts
            </span>
            <span>
              <ClipboardCheck size={18} /> Human-approved response
            </span>
            <span>
              <Activity size={18} /> Persisted execution evidence
            </span>
          </div>
        </div>
        <small>Synthetic manufacturing data · Local sandbox</small>
      </aside>
      <main className="login-main">
        <div className="login-form">
          <span className="eyebrow">OPERATIONS WORKSPACE</span>
          <h2>Sign in to incident control</h2>
          <p>Use a demo account generated by the project bootstrap.</p>
          <form onSubmit={submit}>
            {error && <ErrorBox error={error} />}
            <label>
              Username
              <input
                name="username"
                autoComplete="username"
                required
                autoFocus
                maxLength={100}
                placeholder="Your demo username"
              />
            </label>
            <label>
              Password
              <input
                name="password"
                type="password"
                autoComplete="current-password"
                required
                maxLength={500}
                placeholder="Your generated password"
              />
            </label>
            <button className="button primary full" disabled={busy}>
              {busy ? "Signing in…" : "Open workspace"}
              <ArrowRight size={17} />
            </button>
          </form>
          <div className="login-note">
            <ShieldCheck size={20} />
            <p>
              Access follows your assigned role. Simulated AI and synthetic ERP
              data are clearly identified in the workspace.
            </p>
          </div>
          <small>
            Generated credentials are stored locally in{" "}
            <code>.local/credentials.json</code>. They are never bundled into
            this application.
          </small>
        </div>
      </main>
    </div>
  );
}

const scenarios: {
  id: Scenario;
  title: string;
  icon: typeof Truck;
  description: string;
  journey: string;
}[] = [
  {
    id: "supplier-delay",
    title: "Supplier delay",
    icon: Truck,
    description:
      "A revised material arrival puts production and customer commitments at risk.",
    journey:
      "Verify the message → compare impact → review the supplier response",
  },
  {
    id: "machine-breakdown",
    title: "Machine breakdown",
    icon: Factory,
    description:
      "A machine outage creates a capacity gap. Review a qualified alternative.",
    journey:
      "Verify the outage → inspect capacity → approve synthetic rescheduling",
  },
  {
    id: "quality-issue",
    title: "Quality issue",
    icon: ShieldCheck,
    description:
      "A verified failed inspection traces a defective lot to a pending shipment.",
    journey: "Verify the inspection → trace the lot → request Quality approval",
  },
];
function DemoDialog({
  onClose,
  onRun,
  readOnly,
}: {
  onClose: () => void;
  onRun: (run: Run) => Promise<void>;
  readOnly: boolean;
}) {
  const [busy, setBusy] = useState<Scenario | null>(null),
    [error, setError] = useState<Error | null>(null);
  async function start(scenario: Scenario) {
    setBusy(scenario);
    setError(null);
    try {
      const run = await api<Run>("/api/demo/runs", { scenario });
      await onRun(run);
      onClose();
    } catch (err) {
      setError(err as Error);
    } finally {
      setBusy(null);
    }
  }
  return (
    <Modal title="Start a guided demo" onClose={onClose} wide>
      <div className="modal-content">
        {readOnly && (
          <div className="notice">
            <ShieldCheck size={18} />
            <p>
              Viewer access is read-only. Explore an existing shared demo scope.
              An operational role can start a new scenario.
            </p>
          </div>
        )}
        <p className="muted">
          Each scenario creates a new isolated scope and enters the real n8n
          intake workflow. Results appear when persisted by the backend.
        </p>
        <div className="notice">
          <ShieldCheck size={18} />
          <p>Synthetic data · Simulated AI · Local effects only</p>
        </div>
        {error && <ErrorBox error={error} />}
        <div className="demo-options">
          {scenarios.map(
            ({ id, title, icon: Icon, description, journey }, i) => (
              <button
                key={id}
                className="demo-option"
                disabled={!!busy || readOnly}
                onClick={() => void start(id)}
              >
                <span className="demo-icon">
                  <Icon size={23} />
                </span>
                <span className="demo-copy">
                  <small>SCENARIO 0{i + 1}</small>
                  <strong>{title}</strong>
                  <span>{description}</span>
                  <em>{journey}</em>
                </span>
                <span className="demo-arrow">
                  {busy === id ? (
                    <RefreshCw className="spin" size={19} />
                  ) : (
                    <ArrowRight size={20} />
                  )}
                </span>
              </button>
            ),
          )}
        </div>
        <p className="footnote">
          A demo starts analysis; it does not approve consequential actions. The
          responsible role reviews the exact plan before execution.
        </p>
      </div>
    </Modal>
  );
}
function RunTracker({
  run,
  refresh,
  onDismiss,
}: {
  run: Run;
  refresh: number;
  onDismiss: () => void;
}) {
  const query = useQuery<RecordData>(
    scoped(`/api/source-events/${run.source_event_id}`, run.scope_id),
    refresh,
    2500,
  );
  const event = query.data;
  return (
    <div className="run-tracker" aria-live="polite">
      <span className="tracker-icon">
        <Activity size={20} />
      </span>
      <div>
        <strong>Guided run</strong>
        <p>
          {event ? (
            <>
              <Badge value={event.status} />
              <span className="inline-label">Analysis job</span>
              <Badge value={event.job_status} />
            </>
          ) : (
            "Waiting for a persisted source status…"
          )}
        </p>
        <small>
          Event <code>{run.source_event_id}</code> · Job{" "}
          <code>{run.job_id}</code>
        </small>
        {Array.isArray(event?.review_reasons) && (
          <p>{event.review_reasons.map(string).join(" · ")}</p>
        )}
        {query.error && <p role="alert">{query.error.message}</p>}
      </div>
      {event?.incident_id ? (
        <a
          className="button subtle"
          href={`#/incidents/${string(event.incident_id)}`}
        >
          View incident
          <ArrowRight size={16} />
        </a>
      ) : null}
      <button
        className="icon-button"
        aria-label="Dismiss guided run status"
        onClick={onDismiss}
      >
        <X size={18} />
      </button>
    </div>
  );
}
export default function App() {
  const [session, setSession] = useState<Session | null>(null),
    [booting, setBooting] = useState(true),
    [authError, setAuthError] = useState<Error | null>(null);
  const [scopeId, setScopeId] = useState(""),
    [scopeRefresh, setScopeRefresh] = useState(0),
    [refresh, setRefresh] = useState(0),
    [demo, setDemo] = useState(false),
    [mobile, setMobile] = useState(false),
    [run, setRun] = useState<Run | null>(null);
  const navigationToggle = useRef<HTMLButtonElement>(null);
  const navigationClose = useRef<HTMLButtonElement>(null);
  const closeNavigation = useCallback(() => {
    setMobile(false);
    navigationToggle.current?.focus();
  }, []);
  const route = useRoute();
  const sessionIdentity = session
    ? `${session.user.id}:${session.user.role}`
    : "";
  const scopeQuery = useQuery<{ items: Scope[] }>(
    session ? "/api/scopes" : null,
    scopeRefresh,
    10000,
    sessionIdentity,
  );
  const scopes = scopeQuery.data?.items || session?.scopes || [];
  const kpis = useQuery<Kpis>(
    session && scopeId ? scoped("/api/dashboard", scopeId) : null,
    refresh,
    5000,
    sessionIdentity,
  );
  useEffect(() => {
    let active = true;
    api<Session>("/api/auth/me")
      .then((value) => {
        if (active) {
          setCsrf(value.csrf_token || "");
          setScopeId(restoreScope(value, value.scopes || []));
          setSession(value);
        }
      })
      .catch((error) => {
        if (active && error.status !== 401) setAuthError(error);
      })
      .finally(() => {
        if (active) setBooting(false);
      });
    return () => {
      active = false;
    };
  }, []);
  useEffect(() => {
    if (session && scopes.length && !scopeId)
      setScopeId(restoreScope(session, scopes));
  }, [scopes, scopeId, session]);
  useEffect(() => {
    setMobile(false);
  }, [route]);
  useEffect(() => {
    if (!mobile) return;
    navigationClose.current?.focus();
    const onEscape = (event: KeyboardEvent) => {
      if (event.key === "Escape" && !event.defaultPrevented) {
        event.preventDefault();
        closeNavigation();
      }
    };
    document.addEventListener("keydown", onEscape);
    return () => document.removeEventListener("keydown", onEscape);
  }, [mobile, closeNavigation]);
  async function logout() {
    try {
      await api("/api/auth/logout", {});
      setCsrf("");
      setSession(null);
      setScopeId("");
      setRun(null);
      location.hash = "/overview";
    } catch (error) {
      setAuthError(error as Error);
    }
  }
  async function onRun(value: Run) {
    setRun(value);
    setScopeRefresh((n) => n + 1);
    setScopeId(value.scope_id);
    if (session) rememberScope(session, value.scope_id);
    setRefresh((n) => n + 1);
    location.hash = "/overview";
  }
  function changeScope(id: string) {
    if (!session || !scopes.some((scope) => scope.id === id)) return;
    setScopeId(id);
    rememberScope(session, id);
    setRun(null);
    location.hash = "/overview";
  }
  if (booting)
    return (
      <div className="boot">
        <Loading>Checking your session…</Loading>
      </div>
    );
  if (!session)
    return (
      <Login
        onLogin={(value) => {
          setScopeId(restoreScope(value, value.scopes || []));
          setSession(value);
          setAuthError(null);
          setScopeRefresh((n) => n + 1);
        }}
      />
    );
  const page = route.startsWith("/incidents/")
    ? "detail"
    : route === "/approvals"
      ? "approvals"
      : route === "/reliability"
        ? "reliability"
        : "overview";
  const scope = scopes.find((item) => item.id === scopeId);
  const common = {
    scopeId,
    refresh,
    session,
    onRefresh: () => setRefresh((n) => n + 1),
  };
  return (
    <div className="app-shell">
      <a
        className="skip-link"
        href="#main-content"
        onClick={(event) => {
          event.preventDefault();
          document.getElementById("main-content")?.focus();
        }}
      >
        Skip to content
      </a>
      <aside className={`sidebar ${mobile ? "open" : ""}`}>
        <Brand />
        <button
          ref={navigationClose}
          className="icon-button mobile-nav-close"
          aria-label="Close navigation"
          onClick={closeNavigation}
        >
          <X size={18} />
        </button>
        <div className="sidebar-kicker">WORKSPACE</div>
        <nav
          id="workspace-navigation"
          aria-label="Main navigation"
          onClick={() => {
            if (mobile) closeNavigation();
          }}
        >
          <a
            href="#/overview"
            className={page === "overview" || page === "detail" ? "active" : ""}
          >
            <LayoutDashboard size={19} />
            <span>Overview</span>
          </a>
          <a
            href="#/approvals"
            className={page === "approvals" ? "active" : ""}
          >
            <ClipboardCheck size={19} />
            <span>Approval inbox</span>
            {kpis.data && kpis.data.pending_approvals > 0 && (
              <span className="nav-count">{kpis.data.pending_approvals}</span>
            )}
          </a>
          <a
            href="#/reliability"
            className={page === "reliability" ? "active" : ""}
          >
            <Activity size={19} />
            <span>Reliability</span>
          </a>
        </nav>
        <div className="sidebar-bottom">
          <div className="environment-label">
            <span className="status-dot" />
            <b>{label(kpis.data?.profile || "DEMO_LOCAL")}</b>
            <p>Isolated synthetic operations</p>
          </div>
          <div className="sidebar-user">
            <span className="avatar">
              {session.user.username.slice(0, 2).toUpperCase()}
            </span>
            <div>
              <strong>{session.user.username}</strong>
              <small>{label(session.user.role)}</small>
            </div>
            <button
              className="icon-button"
              aria-label="Sign out"
              onClick={() => void logout()}
            >
              <LogOut size={17} />
            </button>
          </div>
        </div>
      </aside>
      {mobile && (
        <button
          className="nav-backdrop"
          aria-label="Dismiss navigation"
          onClick={closeNavigation}
        />
      )}
      <div className="workspace">
        <header className="topbar">
          <div className="topbar-start">
            <button
              ref={navigationToggle}
              className="icon-button mobile-menu"
              aria-label="Toggle navigation"
              aria-expanded={mobile}
              aria-controls="workspace-navigation"
              onClick={() => {
                if (mobile) closeNavigation();
                else setMobile(true);
              }}
            >
              <Menu size={21} />
            </button>
            <span className="breadcrumb">
              Operations <ChevronRight size={14} />
              <b>
                {page === "detail"
                  ? "Incident detail"
                  : page === "approvals"
                    ? "Approval inbox"
                    : label(page)}
              </b>
            </span>
          </div>
          <div className="topbar-actions">
            <label className="scope-select">
              <span>Demo scope</span>
              <select
                value={scopeId}
                onChange={(e) => changeScope(e.target.value)}
                aria-label="Demo scope"
              >
                {!scopes.length && <option value="">No scopes yet</option>}
                {scopes.map((item) => (
                  <option key={item.id} value={item.id}>
                    {item.name} · {item.id.slice(0, 8)}
                  </option>
                ))}
              </select>
            </label>
            <button className="button primary" onClick={() => setDemo(true)}>
              <Play size={15} />
              Run demo
            </button>
          </div>
        </header>
        <div className="mode-strip">
          <span>
            <ShieldCheck size={14} />
            <b>{kpis.data?.ai_mode || "simulated AI"}</b>
            <i /> Synthetic ERP data <i /> Local sandbox
          </span>
          <span>
            {kpis.data
              ? `Demo clock · ${date(kpis.data.clock)} Bangkok`
              : "Waiting for the scope data clock"}
          </span>
        </div>
        <main id="main-content" tabIndex={-1}>
          <div className="page-heading">
            <div>
              <span className="eyebrow">
                {scope?.name || "ISOLATED DEMO WORKSPACE"}
              </span>
              <h1>
                {page === "detail"
                  ? "Incident detail"
                  : page === "approvals"
                    ? "Approval inbox"
                    : page === "reliability"
                      ? "Reliability"
                      : "Operations overview"}
              </h1>
              <p>
                {page === "detail"
                  ? "Follow the facts, assessment and response in one place."
                  : page === "approvals"
                    ? "Review exactly what will happen before an action is released."
                    : page === "reliability"
                      ? "Persisted execution evidence and controlled recovery."
                      : "Prioritize operational impact. Keep every decision traceable."}
              </p>
            </div>
            <button
              className="button subtle"
              onClick={() => setRefresh((n) => n + 1)}
            >
              <RefreshCw size={16} />
              Refresh
            </button>
          </div>
          {authError && <ErrorBox error={authError} />}{" "}
          {scopeQuery.error && (
            <ErrorBox
              error={scopeQuery.error}
              retry={() => setScopeRefresh((n) => n + 1)}
            />
          )}{" "}
          {run?.scope_id === scopeId && (
            <RunTracker
              run={run}
              refresh={refresh}
              onDismiss={() => setRun(null)}
            />
          )}{" "}
          {!scopeId ? (
            scopeQuery.loading ? (
              <Loading />
            ) : (
              <Empty
                title="Your workspace is ready"
                action={
                  <button
                    className="button primary"
                    onClick={() => setDemo(true)}
                  >
                    <Play size={16} />
                    Choose a scenario
                  </button>
                }
              >
                Start a guided demo to create an isolated scope with synthetic
                data. The dashboard will show the actual workflow results.
              </Empty>
            )
          ) : page === "overview" ? (
            <Overview {...common} kpis={kpis} onDemo={() => setDemo(true)} />
          ) : page === "detail" ? (
            <IncidentDetail
              {...common}
              incidentId={route.slice("/incidents/".length)}
              onRun={onRun}
            />
          ) : page === "approvals" ? (
            <Approvals {...common} />
          ) : (
            <Reliability {...common} />
          )}
          <footer className="page-footer">
            <span>AI Production Incident Control</span>
            <span>
              All times Bangkok (UTC+7) · Whole open-position values · Demo
              policy
            </span>
          </footer>
        </main>
      </div>
      {demo && (
        <DemoDialog
          onClose={() => setDemo(false)}
          onRun={onRun}
          readOnly={session.user.role === "viewer"}
        />
      )}
    </div>
  );
}

export type ViewProps = {
  scopeId: string;
  refresh: number;
  session: Session;
  onRefresh: () => void;
};
